// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk_i5IH8x582n1jarnIkn_xhcPGLR_n-M',
    appId: '1:571167039175:web:ab548828686d02889c28e2',
    messagingSenderId: '571167039175',
    projectId: 'projectshub-309b9',
    authDomain: 'projectshub-309b9.firebaseapp.com',
    storageBucket: 'projectshub-309b9.appspot.com',
    measurementId: 'G-71PVEYLB9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcWS1ocEJL4lgwQA40ZXRCPJieJztMCw',
    appId: '1:571167039175:android:437e36a10bca6d5e9c28e2',
    messagingSenderId: '571167039175',
    projectId: 'projectshub-309b9',
    storageBucket: 'projectshub-309b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtbb2j1S8WOkkN0TfTJxGdjjwfv4bK0A',
    appId: '1:571167039175:ios:7314471646a702a39c28e2',
    messagingSenderId: '571167039175',
    projectId: 'projectshub-309b9',
    storageBucket: 'projectshub-309b9.appspot.com',
    iosClientId:
        '571167039175-jrnb4b4al0ftrcqshvlfbfv013dal0nm.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectshub1',
  );
}
